# Generated by Django 4.2.1 on 2023-05-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filmyWEB", "0003_film_imdb_rating_film_opis_film_plakat_film_premiera"),
    ]

    operations = [
        migrations.CreateModel(
            name="DodatkoweInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("czas_trwania", models.PositiveIntegerField(default=0)),
                (
                    "gatunek",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "Kryminał"),
                            (1, "Horror"),
                            (0, "Inne"),
                            (2, "Komedia"),
                            (3, "Sci-fi"),
                            (4, "Dramat"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="dodatkowe",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filmyWEB.dodatkoweinfo",
            ),
        ),
    ]
