# Generated by Django 4.2.1 on 2023-05-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filmyWEB", "0004_dodatkoweinfo_film_dodatkowe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dodatkoweinfo",
            name="gatunek",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Inne"),
                    (4, "Dramat"),
                    (1, "Horror"),
                    (2, "Komedia"),
                    (3, "Sci-fi"),
                    (5, "Kryminał"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="Ocena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recenzja", models.TextField(blank=True, default="")),
                ("gwiazdki", models.PositiveSmallIntegerField(default=5)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="filmyWEB.film"
                    ),
                ),
            ],
        ),
    ]
