# Generated by Django 4.2.1 on 2023-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmyWEB", "0005_alter_dodatkoweinfo_gatunek_ocena"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dodatkoweinfo",
            name="gatunek",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "Sci-fi"),
                    (5, "Kryminał"),
                    (1, "Horror"),
                    (0, "Inne"),
                    (2, "Komedia"),
                    (4, "Dramat"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="Aktor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=32)),
                ("nazwisko", models.CharField(max_length=32)),
                ("filmy", models.ManyToManyField(to="filmyWEB.film")),
            ],
        ),
    ]
